services:
  backend:
    container_name: ${ORDER_PAYMENT_ENGINE_SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${ORDER_PAYMENT_ENGINE_APP_PORT}:${ORDER_PAYMENT_ENGINE_APP_PORT}
    command: npm run start:prod-pm2
    env_file:
      - .env
 
