export enum SubtransactionStateEnum {
  HOLD_PROCESSING = 'HOLD_PROCESSING',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  HOLD = 'HOLD',
  CANCEL_PROCESSING = 'CANCELLED_PROCESSING',
  CANCELLED = 'CANCELLED',
  COMPLETE_PROCESSING = 'COMPLETE_PROCESSING',
  COMPLETED = 'COMPLETED',
  ROLLBACK_PROCESSING = 'ROLLBACK_PROCESSING',
  ROLLBACKED = 'ROLLBACKED',
}
